[tool.poetry]
name = "indices-analysis"
version = "0.1.0"
description = ""
authors = ["Riccardo7-DS <riccardo_dercole@yahoo.it>"]
readme = "README.md"

packages = [
    {include = "analysis", from = "src"},
    {include = "ancillary", from = "src"},
    {include = "utils", from = "src"},
    {include = "precipitation", from = "src"},
    {include = "soil_moisture", from = "src"},
    {include = "vegetation", from = "src"},
    {include = "shapefiles", from = "src"}
]

[tool.poetry.dependencies]
python = "^3.9"
zarr = "^2.16.1"
apache-beam = "^2.53.0"
pangeo-forge-recipes = "^0.10.4"
xesmf = "^0.8.2"
torch = "^2.1.2"
geopandas = "^0.14.2"
tqdm = "^4.66.1"
geopy = "^2.4.1"
matplotlib = "^3.8.2"
xarray = "^2024.1.1"
loguru = "^0.7.2"
rasterio = "^1.3.9"
gcsfs = "^2023.12.2.post1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
